### ISSUE TITLE
Code Review for Hui En

### ISSUE THREAD

**Issue by hughjazzman** [AY2122S1-CS2113T-F14-1/tp#122]
# @huien77

- [ ] (`storage/Export.java`) Consider adding JavaDoc to these methods in the entire class - they don't look too trivial.

![image](https://user-images.githubusercontent.com/53231968/139524973-f33833d2-1325-46a9-889b-b4330611340f.png)

- [ ] (`storage/Storage.java`) Consider adding JavaDoc in this class as well.

![image](https://user-images.githubusercontent.com/53231968/139525043-da080ba9-c9c3-44a2-9195-5e0db246e3f5.png)

**Comment by huien77** [comment]
added javadoc in pull request #169
