### ISSUE TITLE
[PE-D] Inconsistent Command example in UG.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#125]
Perhaps can be consistent when giving an example in command,

![image.png](https://raw.githubusercontent.com/andrewtkh1/ped/main/files/5f345b22-eeb8-4a59-acbd-43859c211f50.png)

![image.png](https://raw.githubusercontent.com/andrewtkh1/ped/main/files/cd848da7-201b-4e72-b263-5a7627722181.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: andrewtkh1/ped#1

**Comment by STAung07** [comment]
UG change abit can le
