### ISSUE TITLE
[PE-D] Negative numbers throw IndexOutOfBoundsException when changing habits 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#130]
![Screenshot 2021-10-29 at 5.04.37 PM.png](https://raw.githubusercontent.com/leeyikai/ped/main/files/0bf4ca95-ff3f-4f2e-be02-2e198836540e.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: leeyikai/ped#1

**Comment by STAung07** [comment]
Same as #143
