### ISSUE TITLE
[PE-D] Editing of habit

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#131]
Perhaps can explain where to find index_habits? *applies for other functions that require index too.

![image.png](https://raw.githubusercontent.com/andrewtkh1/ped/main/files/0c2b6234-64c6-4cd4-9466-c142093168cf.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: andrewtkh1/ped#4

**Comment by STAung07** [comment]
didn't i explain? if i didn't explain can just add it into UG - Daren
