### ISSUE TITLE
[PE-D] Unable to recover from error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#135]
W.R.T to Issue #5. Upon trying to restart program, it crashes immediately upon startup.

*to Fix, i had to manually delete the habit in the txt files.

![image.png](https://raw.githubusercontent.com/andrewtkh1/ped/main/files/6b3d4a43-f379-4ed6-b3e6-b09d50c2f533.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: andrewtkh1/ped#6

**Comment by STAung07** [comment]
Fixed by Huien! Good Job Huien! True MVP of Storage
