### ISSUE TITLE
[PE-D] Help list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#138]
The help list should either stay permanently in the main application menu, or we should be able to pull it up. As the commands are rather complicated and I found myself struggling to input the correct commands. Constantly having to type in "help" in between typing in commands.

![image.png](https://raw.githubusercontent.com/ChuaXiongWei/ped/main/files/f19f3052-0e60-4a95-a571-e39fbcb68bf3.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ChuaXiongWei/ped#1

**Comment by STAung07** [comment]
It will take up a lot of space. Not feasible. -Daren
