### ISSUE TITLE
[PE-D] The command prompt seems laggy

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#141]
The command prompt seems laggy and affects the user experience. Is there way to make it respond faster?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Rrraaaeee/ped#3

**Comment by STAung07** [comment]
It's not laggy I purposely made it that way. Is there a way to make it any faster? yes. I can make it faster - Daren
