### ISSUE TITLE
[PE-D] Incorrect storage for setting name when name includes "/"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#145]
![Screenshot 2021-10-29 at 5.16.37 PM.png](https://raw.githubusercontent.com/leeyikai/ped/main/files/df388cfc-2748-49f2-922d-81ec92da2b73.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: leeyikai/ped#5

**Comment by STAung07** [comment]
Same as #163
