### ISSUE TITLE
[PE-D] Able to edit date to before start date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#147]
Able to edit Goal1's date to before start date.

![image.png](https://raw.githubusercontent.com/andrewtkh1/ped/main/files/5f3a9dc9-bc0e-4883-9d11-21f5e1abf8f7.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: andrewtkh1/ped#9

**Comment by STAung07** [comment]
Same as #164
