### ISSUE TITLE
[PE-D] Update function does not update habits despite its existence within a set goal

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#149]
As seen from here, the first goal contains two habits

![Capture.JPG](https://raw.githubusercontent.com/Poopies99/ped/main/files/487e0946-ccfc-4c9f-80c8-96fecaf8b791.JPG)

However, when trying to update the interval, program does not allow 

![Capture.JPG](https://raw.githubusercontent.com/Poopies99/ped/main/files/56f84dfc-8236-4d38-8c6b-d3638997e29b.JPG)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Poopies99/ped#3

**Comment by STAung07** [comment]
Change error message for more clarity when user types in wrong command.
