### ISSUE TITLE
[PE-D] Manual edit of file to change Goal name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#154]
Able to manually edit the file to make all the goal name the same

![image.png](https://raw.githubusercontent.com/andrewtkh1/ped/main/files/efee1b2a-3b72-400a-bab6-a69e7521aa82.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: andrewtkh1/ped#11

**Comment by STAung07** [comment]
Fixed!
