### ISSUE TITLE
[PE-D] Completion status not updated after changing interval

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-1/tp#155]
![Screenshot 2021-10-29 at 5.28.43 PM.png](https://raw.githubusercontent.com/leeyikai/ped/main/files/cb4595b8-353f-456b-92c9-6be9b559d612.png)
![Screenshot 2021-10-29 at 5.29.47 PM.png](https://raw.githubusercontent.com/leeyikai/ped/main/files/2f8c78da-e3e3-4dd0-953c-cee21b33bbeb.png)

Can be replicated by completing 1 repetition, then changing interval to 0

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: leeyikai/ped#7

**Comment by STAung07** [comment]
By changing an interval, all data before will be saved and a new interval will be created from the date of change will be created. Mention in UG -> Desired Effect
Interval cannot be changed to 0
